### ISSUE TITLE
Crash on connection problems

### ISSUE THREAD

**Issue by ensiform** [Awpteamoose/discord-pugbot#5]
```
Error: Uncaught, unspecified "error" event. ([object Object])
    at Client.emit (events.js:166:17)
    at WebSocketConnection.onError (C:\Users\USER\AppData\Roaming\npm\node_modules\discord-pugbot\node_modules\discord.js\sr
c\client\websocket\WebSocketConnection.js:357:17)
    at process.nextTick (C:\Users\USER\AppData\Roaming\npm\node_modules\discord-pugbot\node_modules\uws\uws.js:80:19)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by metalun4** [comment]
`"dependencies": {
    "babel-polyfill": "6.23.0",
    "discord.js": "11.1.0",
    "ejs": "2.5.6",
    "json5": "0.5.1",
    "moment": "2.17.1",
    "node-json-db": "0.7.3",
    "ramda": "0.23.0",
    "source-map-support": "0.4.11",
    "uws": "0.14.1"
  }` your dependencies section should be looking like this in package.json uws 0.12.0 (older version) not in npm anymore
